backend:
  name: git-gateway
  branch: netlify
  commit_messages:
    create: "create {{collection}} `{{slug}}`"
    update: "update {{collection}} `{{slug}}`"
    delete: "delete {{collection}} `{{slug}}`"
    uploadMedia: "[skip ci] upload `{{path}}`"
    deleteMedia: "[skip ci] delete `{{path}}`"

local_backend: true

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "文章"
    folder: "content/post/"
    create: true
    slug: "index"
    media_folder: ""
    path: "{{path}}/index"
    editor:
      preview: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "路径", name: "path", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "描述", name: "description", widget: "string" }
      - {
          label: "标签",
          name: Tags,
          widget: tags,
          separator: ",",
          required: false,
        }
      - { label: "正文", name: "body", widget: "markdown" }
      - { label: "图片", name: "image", widget: "image", required: false }

  - name: "pages"
    label: "页面"
    files:
      - file: "content/pages/about/index.md"
        label: "关于我"
        name: "about"
        fields:
          - {
              label: "标题",
              name: "title",
              widget: "hidden",
              default: "关于我",
            }
          - {
              label: "日期",
              name: "date",
              widget: "hidden",
              default: "2021-10-29 14:59:00",
            }
          - {
              label: "日期",
              name: "path",
              widget: "hidden",
              default: "/about",
            }
          - {
              label: "列表忽略",
              name: "ignore_in_list",
              widget: "hidden",
              default: true,
            }
