backend:
  name: git-gateway
  branch: netlify

local_backend: true

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/post"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "index"
    editor:
      preview: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "描述", name: "description", widget: "string" }
      - { label: "正文", name: "body", widget: "markdown" }
      - { label: "图片", name: "image", widget: "image" }
