locale: "cn"
backend:
  name: git-gateway
  branch: netlify
  commit_messages:
    create: "create {{collection}} `{{slug}}`"
    update: "update {{collection}} `{{slug}}`"
    delete: "delete {{collection}} `{{slug}}`"
    uploadMedia: "[skip ci] upload `{{path}}`"
    deleteMedia: "[skip ci] delete `{{path}}`"

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts/"
    create: true
    slug: "index"
    media_folder: ""
    path: "{{path}}/index"
    editor:
      preview: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "路径", name: "path", widget: "string", required: false }
      - { label: "日期", name: "date", widget: "datetime" }
      - {
          label: "描述",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "标签",
          name: "tags",
          widget: tags,
          separator: ",",
          required: false,
        }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/about/index.md"
        label: "关于我"
        name: "about"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - {
              label: "日期",
              name: "date",
              widget: "datetime",
              default: "2021-10-29 14:59:00",
            }
          - {
              label: "路径",
              name: "path",
              widget: "string",
              default: "/about",
              pattern: ["^/.+", "必须为路径"],
            }
          - {
              label: "列表忽略",
              name: "ignore_in_list",
              widget: "hidden",
              default: true,
            }
          - { label: "正文", name: "body", widget: "markdown" }
