backend:
  name: git-gateway
  branch: netlify
  commit_messages:
    create: "create {{collection}} `{{slug}}`"
    update: "update {{collection}} `{{slug}}`"
    delete: "delete {{collection}} `{{slug}}`"
    uploadMedia: "[skip ci] upload `{{path}}`"
    deleteMedia: "[skip ci] delete `{{path}}`"

local_backend: true

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/post/"
    create: true
    slug: "index"
    media_folder: ""
    path: "{{path}}/index"
    editor:
      preview: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "路径", name: "path", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "描述", name: "description", widget: "string" }
      - {
          label: "标签",
          name: Tags,
          widget: tags,
          separator: ",",
          required: false,
        }
      - { label: "正文", name: "body", widget: "markdown" }
      - { label: "图片", name: "image", widget: "image", required: false }
